language: php

php:
  - 5.5
  - nightly

services: mongodb

before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install
  - cp ./.env.example ./.env
  - php artisan db:seed
